In [5]:
import numpy as np
import matplotlib.pyplot as plt
import random as rand
import numpy as np
import pandas as pd
import string
from stochastic.processes.continuous import FractionalBrownianMotion

In [6]:
outcome = pd.DataFrame({
    x: [rand.normalvariate(5, 0.2) for _ in range(100)] for x in
    ["APPL", "GOOG", "MSFT", "XLS", "AMZN", "AWW", "FB", "TWTR", "YHOO"]
})
outcome

,APPL,GOOG,MSFT,XLS,AMZN,AWW,FB,TWTR,YHOO
0,4.850461,4.842485,5.079850,4.508795,4.638930,4.969724,4.609291,5.045235,4.726835
1,4.759606,5.273596,5.120818,4.702989,5.003208,5.110938,4.976966,5.366925,4.946151
2,5.077758,5.118537,4.808451,4.765186,5.144160,5.283364,5.050848,4.898532,4.681555
3,5.076467,4.889830,5.263300,4.957675,4.950002,4.855895,4.819793,4.858117,5.265965
4,4.769061,4.831583,5.403319,4.813228,4.823940,5.075067,4.789489,4.882332,4.983370
...,...,...,...,...,...,...,...,...,...
95,4.692166,5.039178,4.486444,5.415718,4.889789,4.727941,5.221825,5.010913,5.098278
96,5.066495,5.267220,4.989758,5.210866,4.871472,5.159027,5.099447,4.922722,5.119777
97,4.927826,4.832543,5.007781,4.731647,5.004558,5.021696,5.261588,4.806426,4.863610
98,5.136732,5.033055,4.799375,4.849797,4.899866,4.876686,4.966852,4.924201,5.322377
99,5.068508,4.562872,5.066666,4.842079,4.974920,5.000654,5.252214,4.886070,4.989888

In [12]:
10 * 100000

1000000